
/**
 * Created by okunetc on 19.01.2017.
 */
export enum UnitType{
    // Phalanx,
    // Swordsman,
    // Pathfinder,
    // TheutatesThunder,
    // Druidrider,
    // Haeduan,
    // RamG,
    // Trebuchet,
    // Chieftain,
    //
    // Clubswinger,
    // Spearman,
    // Axeman,
    // Scout,
    // Paladin,
    // TeutonicKnight,
    // RamT,
    // Catapult,
    // Chief,
    //
    // Legionnaire,
    // Praetorian,
    // Imperian,
    // EquitesLegati,
    // EquitesImperatoris,
    // EquitesCaesaris,
    // BatteringRam,
    // FireCatapult,
    // Senator,

    Phalanx=<any>"Phalanx",
    Swordsman = <any>"Swordsman",
    Pathfinder = <any>"Pathfinder",
    TheutatesThunder = <any>"TheutatesThunder",
    Druidrider = <any>"Druidrider",
    Haeduan=<any>"Haeduan",
    RamG=<any>"RamG",
    Trebuchet=<any>"Trebuchet",
    Chieftain=<any>"Chieftain",

    Clubswinger=<any>"Clubswinger",
    Spearman=<any>"Spearman",
    Axeman=<any>"Axeman",
    Scout=<any>"Scout",
    Paladin = <any>"Paladin",
    TeutonicKnight = <any>"TeutonicKnight",
    RamT = <any>"RamT",
    Catapult = <any>"Catapult",
    Chief = <any>"Chief",

    Legionnaire=<any>"Legionnaire",
    Praetorian=<any>"Praetorian",
    Imperian=<any>"Imperian",
    EquitesLegati=<any>"EquitesLegati",
    EquitesImperatoris=<any>"EquitesImperatoris",
    EquitesCaesaris=<any>"EquitesCaesaris",
    BatteringRam=<any>"BatteringRam",
    FireCatapult=<any>"FireCatapult",
    Senator=<any>"Senator",

}